### ISSUE TITLE
Can't install/build on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by tehKapa** [chenjiandongx/kubectl-images#10]
Hi, 
there is no way to install this kubectl plugin on my macOS Catalina 10.15.7 (go version go1.15.3 darwin/amd64)

If I try to install it through krew, I've this error:

```
kubectl krew install images

Updated the local copy of plugin index.
F1020 17:44:43.646296   69936 root.go:52] failed to load plugin "images" from the index: platform ({Head: URI:https://github.com/chenjiandongx/kubectl-images/releases/download/v0.3.0/kubectl-images_darwin_amd64.tar.gz Sha256:48ee14e36375c7a717c78284525893afe652fc2694c44dc32dece78a17434f72 Selector:&LabelSelector{MatchLabels:map[string]string{arch: amd64,os: darwin,},MatchExpressions:[],} Files:[] Bin:kubectl-images}) is badly constructed: can't have a plugin without specifying file operations
```

If I try to build it through downloaded sources, I've this error:
```
kubectl images -A
exec format error
```

If I try to build it from git clone,  I've an error during execution:
```
kubectl images -A
Error: unknown command "images" for "kubectl"
Run 'kubectl --help' for usage.
```

Go version too up-to-date?

**Comment by chenjiandongx** [comment]
@tehKapa What's your krew version?

I have sent a new PR to krew-index to update kubectl-images index yaml and I think that will be a workaround.

**Comment by tehKapa** [comment]
> @tehKapa What's your krew version?

v0.2.1

> You can update your krew index from remote and then retry it again : )

Thanks!
