### ISSUE TITLE
Ability to show image digest by passing --digest flag

### ISSUE THREAD

**Issue by Dentrax** [chenjiandongx/kubectl-images#16]
The idea here is to show image digest in the output table. In the cluster, there can be same image  name with exactly _same tag_ but still there is a change that images can be _different_. [^1] So, It would be nice to show image digests additionally.

As a reference, I can drop `$ crane digest <IMAGE>` [function here.](https://github.com/google/go-containerregistry/blob/890d5b362eb849db112bb36543014e4e5e57ef8d/cmd/crane/cmd/digest.go#L54-L60)

@developer-guy

[^1]: https://www.mikenewswanger.com/posts/2020/docker-image-digests/

**Comment by chenjiandongx** [comment]
kubectl-images retrieve the images detailed from `kubectl get` command, but there is only `image`/`imagePullPolicy` in its output.

```doc
   image	<string>
     Docker image name. More info:
     https://kubernetes.io/docs/concepts/containers/images This field is
     optional to allow higher level config management to default or override
     container images in workload controllers like Deployments and StatefulSets.

   imagePullPolicy	<string>
     Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always
     if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated.
     More info:
     https://kubernetes.io/docs/concepts/containers/images#updating-images
```

**Comment by Dentrax** [comment]
Hmmm, maybe we can import go-containerregistry and use [crane digest](https://github.com/google/go-containerregistry/blob/master/cmd/crane/cmd/digest.go) command to get digest.

**Comment by chenjiandongx** [comment]
But I don't think that is a good approach, in that scenario, it looks like that must have `crane` command installed.

**Comment by Dentrax** [comment]
It doesn't need to be installed, we can use it as a dependency. It talks the remote docker registry v2 API under the hood.

**Comment by chenjiandongx** [comment]
👍
Could you file a new PR  to support that new feature?

**Comment by Dentrax** [comment]
Not making any promises, but I'll try. Is creating a new `--digest` flag makes sense to you? By doing so, we are able to check whether _that image_ exists in the remote registry. Should we add some colorized output? Red, if not exist, for example.

**Comment by chenjiandongx** [comment]
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/19553554/154826746-93bd7c05-ef94-4d3e-9fb8-1a7f2f5c315b.png">

or you can try to add a new column(no.5)

**Comment by Dentrax** [comment]
It wouldn't fit in the terminal since it's 64 digits. What about inserting it just below the image name?

```
myimagename:latest
(0x012335...)
```

**Comment by chenjiandongx** [comment]
> It wouldn't fit in the terminal since it's 64 digits. What about inserting it just below the image name?
> 
> ```
> myimagename:latest
> (0x012335...)
> ```

agree
