### ISSUE TITLE
Table output does not fit terminal: introduce tree output type

### ISSUE THREAD

**Issue by Dentrax** [chenjiandongx/kubectl-images#19]
I like using this plugin, and it's very lifesaver. But one feature that would be nice to add is that `tree` output format. Everytime I run `kubectl images` I have to make fonts smaller by pressing <kbd>CMD + -</kbd> key repeatedly. So I thought we can add new output type: `tree`:

```
Deployment/foo
 └─Pod/foo-6f67dcc579-znb57
  └─Container/app1
    └─ $IMAGE1
  └─Container/app2
    └─ $IMAGE2
```

Thoughts? @chenjiandongx

**Comment by chenjiandongx** [comment]
v0.4.0 has been released, the new version will supports json/yaml format which will solved your problems. See the readme for more details

**Comment by Dentrax** [comment]
Thanks, @chenjiandongx!

But seems I can't parse the outputs in JSON/YAML formats:

```
$ k images -o yaml | yq
Error: bad file '-': yaml: line 1: did not find expected key

$ k images -o json | jq
parse error: Invalid numeric literal at line 1, column 9
```

That's because it prints additional `summary` log which breaks the entire format:

```
$ k images -o json
[Summary]: 1 namespaces, 80 pods, 97 containers and 12 different images
[
 {
  "pod": "coredns-bbb7d66cd-qntdp",
  "container": "coredns",
  "image": "k8s.gcr.io/coredns/coredns:v1.8.0"
 },
 ...
 
$ k images -o yaml
[Summary]: 1 namespaces, 80 pods, 97 containers and 12 different images
```

**Comment by Dentrax** [comment]
Wrote the following script to simplify the output:

```
$ k images -o json | tail -n +2 | jq '[.[] | .image] | unique | sort' | jq -r '.[]'

docker.io/library/nginx:1.19
k8s.gcr.io/coredns/coredns:v1.8.0
...
```

**Comment by chenjiandongx** [comment]
@Dentrax 

How about adding a `--no-summary` to disable summary output?

**Comment by Dentrax** [comment]
I think we should not print out any log by default if we pass `-o` flag. Additional `--no-summary` flag would a bit ambiguous in this context I think.

**Comment by chenjiandongx** [comment]
great! that's a better idea.

**Comment by chenjiandongx** [comment]
please upgrade to v0.5.2 :)
