### ISSUE TITLE
Connection errors are masked by "no images matched" error

### ISSUE THREAD

**Issue by ahmetb** [chenjiandongx/kubectl-images#20]
My kubectl command normally fails due to an error (about credentials plugin etc because I am not on company VPN).

But the error I get from `kubectl images -A` is:

```
[Oh...] Execute command error: exit status 1
[Oh...] No images matched!
```

two problems here:

1. original error is swallowed / making me think it actually queried fine
2. error is printed to stdout, which is a bad idea because the cmd was returning when I piped its output to `kubectl images -A |grep IMAGENAME` it was printing nothing (makes me think it queried fine again).

**Comment by chenjiandongx** [comment]
kubectl-images v0.4.0 has been released, the new version will solved problems you mentioned

all error will be captured and redirect to stderr, and the new release will supports json/yaml output format. please see README  for more details.

```shell
$ kubectl images -n kube-system -C nonexist | grep expected
[Oh...] Execute command error: exit status 1, error: context "nonexist" does not exist
```
