### ISSUE TITLE
--kubeconfig flag is unknown

### ISSUE THREAD

**Issue by MaximusAccount** [chenjiandongx/kubectl-images#9]
Once i'm trying to execute kubectl images with a flag --kubeconfig (kubectl images -A --kubeconfig <blablabla> )to path a specific cluster config to be executed with i'm receiving next message

_unknown flag: --kubeconfig
--
_| Error: unknown flag: --kubeconfig__

Please add a support of --kubeconfig flag

**Comment by chenjiandongx** [comment]
@MaximusAccount 

I will add `--kubeconfig` flag support in the next version. Stay tuned.

**Comment by chenjiandongx** [comment]
ping @MaximusAccount 

The PR has been merged https://github.com/kubernetes-sigs/krew-index/pull/657, 

Now you can execute the `kubectl krew upgrade images` commands to use it.
